# Generated by Django 2.0.7 on 2021-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neki', '0003_product_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
