# Generated by Django 2.0.7 on 2021-02-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neki', '0004_auto_20210227_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.BooleanField(default=True),
        ),
    ]
